on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node Version'
        required: true
        type: string

jobs:
  docker-compose:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Containers
        run: docker-compose "docker-compose.yml" up -d --build
      
      - name: Upload visual test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: visual-regression-differences
          path: ./packages/core-components/__snapshots__/__diff_output__
          retention-days: 10